kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
- name: env
  image: busybox
  commands:
  - env
  when:
    event:
    - promote
    target:
    - example

trigger:
  branch:
  - main
