kind: pipeline
type: docker
name: default

trigger:
  branch:
  - main

platform:
  os: linux
  arch: arm64

steps:
- name: private
  image: jimsheldon/alpine-test
  commands:
  - echo "image is private"

image_pull_secrets:
- jimdockercfg
