kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
- name: env
  image: busybox
  commands:
  - env

trigger:
  branch:
  - main

---
kind: pipeline
type: docker
name: amd64

steps:
- name: env
  image: busybox
  commands:
  - env

trigger:
  branch:
  - main

---
kind: pipeline
type: exec
name: windows

platform:
  os: windows
  arch: amd64

node:
  type: t3a-xlarge

steps:
- name: env
  commands:
  - systeminfo

trigger:
  branch:
  - main
