kind: pipeline
type: docker
name: cluster1

node:
  cluster: one

steps:
- name: env
  image: busybox
  commands:
  - env

trigger:
  branch:
  - main

---
kind: pipeline
type: docker
name: cluster2

node:
  cluster: two

steps:
- name: env
  image: busybox
  commands:
  - env

trigger:
  branch:
  - main
