{
   "kind": "pipeline",
   "name": "default",
   "steps": [
      {
         "commands": [
            "echo hello world"
         ],
         "image": "alpine",
         "name": "build"
      }
   ],
   "type": "docker"
}
